### nerdtree
[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTree']

[[plugin]]
repo ='rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = 'source ~/dotfiles/vim/accelerated_jk.lvim'

[[plugins]]
repo = 'rbtnn/puyo.vim'
on_cmd = ['Puyo']

[[plugins]]
repo = 'rbtnn/mario.vim'
on_cmd = ['Mario']
